### ISSUE TITLE
ORDER BY with LIMIT evaluated in wrong order

### ISSUE THREAD

**Issue by psybers** [forcedotcom/phoenix#29]
Using the stock symbol example, if we do these queries:

``` sql
SELECT SYMBOL FROM STOCK_SYMBOL ORDER BY SYMBOL DESC LIMIT 3;
SELECT SYMBOL FROM STOCK_SYMBOL ORDER BY SYMBOL ASC LIMIT 3;
```

One would expect different symbols in each set.  Instead we get this result:

```
SYMBOL     
---------- 
GOOG       
CRM        
AAPL       
SYMBOL     
---------- 
AAPL       
CRM        
GOOG       
```

Which implies that the LIMIT was applied first, then ORDER BY.  I could be wrong but I believe most databases would not evaluate these expressions in that order.

**Comment by madhudhuma** [comment]
Hi,

I am using Phoenix4.4 and facing same issue, When just order by done I get proper data with row count of 100 but on adding **limit 10** row count comes to 6 and I don't get the output in required order. Please let me know if this is supported in Phoenix 4.4.

my queries is of below form

select subscriber, sum(totalbytes) as outertotalbytes from (
	select xyz.subscriber , sum(abcd.total_bytes) as totalbytes 
		from four_g.s1u_abcd_weekly abcd INNER JOIN four_g.s11_xyz_weekly xyz   
		ON abcd.sgw_ip = xyz.sgw_ip AND abcd.user_ip = xyz.user_ip 
		WHERE xyz.report_time between to_date('2016-03-28 09:23:26.46') and to_date('2016-03-31 09:23:26.46')  
		group by xyz.subscriber 
    UNION ALL 
	select xyz.subscriber , sum(abcd.total_bytes) as totalbytes 
		from four_g.s1u_abcd_daily abcd INNER JOIN four_g.s11_xyz_daily xyz   
		ON abcd.sgw_ip = xyz.sgw_ip AND abcd.user_ip = xyz.user_ip 
		WHERE xyz.report_time between to_date('2016-03-28 09:23:26.46') and to_date('2016-03-31 09:23:26.46') 
		group by xyz.subscriber 
) group by subscriber 
order by outertotalbytes desc limit 10;

**Comment by jtaylor-sfdc** [comment]
Please file a JIRA and include the data set (as a CSV or script) to
reproduce the issue.

Also, this Google group is no longer active. Please use our Apache mailing
list instead.

On Mar 31, 2016, at 10:51 PM, madhudhuma <notifications@github.com> wrote:

Hi,

I am using Phoenix4.4 and facing same issue, When just order by done I get
proper data with row count of 100 but on adding *limit 10* row count comes
to 6 and I don't get the output in required order. Please let me know if
this is supported in Phoenix 4.4.

my queries is of below form

select subscriber, sum(totalbytes) as outertotalbytes from (
select xyz.subscriber , sum(abcd.total_bytes) as totalbytes
from four_g.s1u_abcd_weekly abcd INNER JOIN four_g.s11_xyz_weekly xyz

ON abcd.sgw_ip = xyz.sgw_ip AND abcd.user_ip = xyz.user_ip
WHERE xyz.report_time between to_date('2016-03-28 09:23:26.46') and
to_date('2016-03-31 09:23:26.46')

group by xyz.subscriber
UNION ALL
select xyz.subscriber , sum(abcd.total_bytes) as totalbytes
from four_g.s1u_abcd_daily abcd INNER JOIN four_g.s11_xyz_daily xyz

ON abcd.sgw_ip = xyz.sgw_ip AND abcd.user_ip = xyz.user_ip
WHERE xyz.report_time between to_date('2016-03-28 09:23:26.46') and
to_date('2016-03-31 09:23:26.46')
group by xyz.subscriber
) group by subscriber
order by outertotalbytes desc limit 10;

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/forcedotcom/phoenix/issues/29#issuecomment-204257112>
